version: '3.3'

services:
  aclify:
    container_name: "aclify"
    build: .
    depends_on:
      - mysql
      - redis
      - mongo
    networks:
      - aclify-network
    volumes:
      - .:/opt/app/:rw
    command: sh -c 'cd /opt/app && npm install && npm run test'

  mysql:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=aclify
      - MYSQL_ROOT_PASSWORD=aclify
    networks:
      - aclify-network

  redis:
    image: redis:4.0
    container_name: "redis"
    ports:
      - 6379:6379
    networks:
      - aclify-network

  mongo:
    image: mongo:3.6
    container_name: "mongo"
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - aclify-network
